### ISSUE TITLE
Cannot use non ascii word in conf file.

### ISSUE THREAD

**Issue by aristotll** [carueda/tscfg#29]
For example I use non ascii 
```
// 测试 is test in Chinese.
test = "测试" 

```

The generator complains:
```
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:210)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at java.io.Reader.read(Reader.java:140)
	at scala.io.BufferedSource.mkString(BufferedSource.scala:96)
	at tscfg.Main$.generate(Main.scala:133)
	at tscfg.Main$.main(Main.scala:54)
	at tscfg.Main.main(Main.scala)
```

Maybe something wrong  with the default charset tscfg uses?
My file is in UTF-8.

**Comment by carueda** [comment]
Can you attach your failing input file? 
 I just tried your test by copy-n-pasting in a local file and didn't see any complains from the **generator**:

```
$ cat issue29.spec.conf
// 测试 is test in Chinese.
test = "测试"

$ file issue29.spec.conf
issue29.spec.conf: UTF-8 Unicode text


$ tscfg --spec issue29.spec.conf
parsing: issue29.spec.conf
generating: /tmp/ExampleCfg.java

$ file /tmp/ExampleCfg.java
/tmp/ExampleCfg.java: UTF-8 Unicode text


$ cat /tmp/ExampleCfg.java
// generated by tscfg 0.8.3 on Thu Dec 14 10:37:46 PST 2017
// source: issue29.spec.conf

package tscfg.example;

public class ExampleCfg {
  public final java.lang.String test;

  public ExampleCfg(com.typesafe.config.Config c) {
    this.test = c.hasPathOrNull("test") ? c.getString("test") : "测试";
  }
}
```

Is the issue perhaps with the **generated** code when trying to process the input as a concrete configuration?

**Comment by aristotll** [comment]
Thank you for your reply.
It seems I can only reproduce this problem from shell script only (From command line the issue does not exist...
```
$ cat run_new.sh 
#!/usr/bin/env bash
java -jar ./tscfg-0.8.3.jar --spec ./test.conf --pn scala_.hocon --cn TestConf --dd .
```
test.conf with the file contents 
```
$ cat test.conf
// 测试 is test in Chinese.
test = "测试"
```

From https://stackoverflow.com/questions/10846848/why-do-i-get-a-malformedinputexception-from-this-code, I changes my command to
```
java -Dfile.encoding=UTF-8 -jar ./tscfg-0.8.3.jar --spec ./test.conf --pn scala_.hocon --cn TestConf --dd .
``` 
And everythings is ok.

I will close the issue because of the problem does not exist in command line.

**Comment by carueda** [comment]
Yes, strange ... BTW, sorry I didn't show the source of my tscfg script mentioned above, here it is:

```
$ cat ~/bin/tscfg
JAR=~/bin/tscfg-0.8.3.jar
JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_121` java -jar $JAR "$@"
```

Anyway, thanks for the report!  Although it's closed now, I'll try to look into this more closely when time permits.
